(global-set-key "\C-h" `delete-backward-char)
(add-to-list 'default-frame-alist '(fullscreen . maximized))
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(setq org-todo-keywords '((sequence "TODO" "WAIT" "DONE")))
(setq org-todo-keyword-faces
      '(("TODO" . org-warning)
        ("DONE" . (:foreground "RosyBrown" :weight bold))
	("WAIT" . (:foreground "blue" :weight bold))))
